
spring:
#  sql:
#    init:
#      mode: embedded
  config:
    import: application-auth.yml, application-s3.yml
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rcd_oper?useSSL=false&serverTimezone=UTC
    username: root
    password: 89940775

  jpa:
#    defer-datasource-initialization: true # embededDB에 data.sql 사용하기 위함
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #dialect: org.hibernate.dialect.MariaDBDialect
        #dialect: org.hibernate.dialect.H2Dialect
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  web:
    resources:
      static-locations: classpath:/static/



