server:
  port: 8090

spring:
  config:
    import: application-auth.yml, application-s3.yml, application-db.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
        dialect: org.hibernate.dialect.MariaDBDialect
        #dialect: org.hibernate.dialect.H2Dialect
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  web:
    resources:
      static-locations: classpath:/static/



